//
//  Chief.swift
//  Yumood
//
//  Created by apprenant75 on 20/09/2022.
//

import Foundation
import SwiftUI

struct Chef: Identifiable{
    var id = UUID()
    var pictureChef:String
    var nameChef : String
    var prenom : String
    var bioChef : String
    var bioPlat : String
    var itemChef : [String]
    var picRecipe : String
}

var chefAmanda : Chef = Chef(pictureChef: "chefAmanda", nameChef: "Espinosa", prenom: "Leonor",bioChef: "Leonor Espinosa De La Ossa, également connue sous son surnom Leo, est une chef colombienne dont le restaurant Bogotá, Leo Cocina y Cava, proposant une fusion de cuisine colombienne traditionnelle et moderne, l'a attirée pour la première fois à l'attention internationale lors de son ouverture en 2007. [1][2] Espinosa apparaît régulièrement à la télévision colombienne et dirige également les restaurants Leo Cocina y Cava et Misia Son restaurant Leo Cocina y Cava a été classé en 2007 parmi les 82 meilleurs restaurants au monde par Condé Nast Traveler et a été récompensé en 2014 et 2015 comme l'un des meilleurs restaurants de Colombie selon la liste S. Pellegrino des 50 d'Amérique latine. Meilleurs restaurants. En tant que point de repère important, connu pour célébrer la cuisine nationale à travers son menu, Leo Cocina y Cava est un incontournable pour les visiteurs et les voyageurs.", bioPlat: "Avant l’arrivée des colons, la Colombie, le Vénézuela et l’Equateur formaient un même pays qui s’appelait la Gran Colombia. C’est pourquoi nous retrouvons beaucoup de similitudes culturelles d’un pays à l’autre a l’origine, les arepas étaient préparées par les populations natives de la région à même la pierre, où ils les faisaient cuire.Aujourd’hui les arepas se consomment toujours au quotidien. Elles se mangent principalement au petit-déjeuner mais en réalité, chaque famille a sa tradition ! Nous les gourmands de Tierra Latina, nous vous dirons qu’elles peuvent se manger à n’importe quelle heure (avec modération) !", itemChef: ["1", "5 ans ", "1M"], picRecipe: "arepaRica")
var chefPepone : Chef = Chef(pictureChef: "chefMario", nameChef: "Pepone", prenom: "Mario", bioChef: "Né à Bourgoin-Jallieu dans l’Isère en 1981, Mario Pepone découvre l’amour de la cuisine grâce à son arrière-grand-mère : ‘’ Très jeune, je me tourne vers le métier de cuisinier, certainement en hommage à mon arrière-grand-mère qui m’a prouvé que l’amour pouvait se partager autour d’une table Il a vu son amour de la cuisine, du savoir-faire et du partage encouragé par ses professeurs, son maître d’apprentissage et ses employeurs. En 2007, fort de 12 années d’expériences en cuisine semi-gastronomique, traiteur, management, il décide de se mettre à son compte avec son épouse Julie et font l’acquisition d’une petite pizzeria de Gerland à Lyon ‘’ Mamamia Pizza ", bioPlat: "La pizza est née au XVIème siècle dans la ville de Naples en Italie. A cette époque on essayait d’améliorer le goût – un peu fade – des crêpes de pain, avec l’aide de gros sel et de gras de porc.A cette même époque des navigateurs ont rapporté des tomates du Pérou qui petit à petit furent cultivées en Europe. A partir de là, 100 ans s’écoulèrent jusqu’à ce que les tomates finissent en garniture de pizza. Pourtant il fallut attendre le XVIIIème siècle pour que la sauce tomate vienne agrémenter la pizza.", itemChef: ["2", "15 ans ", "2M "], picRecipe: "pizzamargarita")
var chefBali : Chef = Chef(pictureChef: "chefBaliHardik", nameChef: "Hardik", prenom: "Hassan", bioChef:"Cooking began at a very early age back then as a kid. Like most of the kids, I was never much into outdoor sports due to health reasons and hence I had to find activities in-house. Apart from painting and playing state-level chess; cooking took a lot of my time and came to me naturally. I used to watch a lot of travel shows understanding different cultures on how people evolve around food and ingredients which eventually made me do what I am doing today. I pursued my hotel management and wrote my thesis on marketing but kitchens happened to me purely out of my passion to cook and explore more and create more on plates. Food has always been a form of art of expression to me. I used to draw on surfaces as a kid then and I do it today also but on plates, nothing much has changed. " , bioPlat: "“Nasi Goreng” signifie “riz frit”. L'idée de base de ce plat est en fait d'éviter le gaspillage alimentaire car, à l'origine, le riz utiliser pour ce le plat est le reste du dîner ou du déjeuner. Vous trouverez le Nasi Goreng dans presque tous les lieux, du restaurant cinq étoiles à l'étal de rue. Le bon moment pour manger le plat est également très polyvalent; que ce soit pour le petit déjeuner ou le dîner, c'est à vous de décider.", itemChef: ["1", "5 ans ", "1M"], picRecipe: "nasigoreng")
var chefKentRollins : Chef = Chef(pictureChef: "chefKentRollins", nameChef: "Rollins", prenom: "Kent", bioChef: "Welcome to our camp. I’m Kent Rollins, a chuck wagon cook who has cooked for traditional working ranches for over 20 years. Here you’ll find a wide collection of recipes, cowboy culture and cooking tips.", bioPlat: "Le damper est un tourteau traditionnel australien – composé d’un mélange de farine, d’eau (ou de lait) et de sel, cuit dans les cendres d’un feu de camp. Ce pain emblématique, populaire auprès des aborigènes australiens, permet aux travailleurs, aux campeurs et aux colons de survivre dans le désert.", itemChef: ["1", "5 ans ", "1M"], picRecipe: "damper")
var chefMojgan: Chef = Chef(pictureChef: "mojgan", nameChef: "Tashvighi", prenom: "Mojgan", bioChef: "Petite, Mojgan se baladait entre la cuisine et la salle à manger du restaurant de ses grands-parents à Shiraz. Elle aimait ce restaurant, ses sous-sols, ses coins cachés, le va-et-vient des serveurs, le sifflement rassurant du samovar coiffé de la grosse théière, et toutes ces odeurs qui y régnaient en permanence. Arrivée d’Iran en France en 2001, cela fait presque 6 ans que Mojgan s’est installée dans la ville des gones. En 2015 Mojgan, se lance à la conquête de son rêve : Faire de sa passion la cuisine, son métier !Elle débuta en tant que traiteur en vente à domicile, réception et chef à domicile. Elle donnait aussi des cours de cuisine avec toujours cette même envie de partager et de transmettre l’amour de son pays.", bioPlat: "Cuit dans une grande poêle à la manière d’une frittata, le kuku sabzi est un plat traditionnel de la cuisine perse. À la sortie du four, cette galette d’un beau vert profond peut être servie comme plat principal ou en guise d’accompagnement avec du riz. On y ajoute juste assez d’œufs afin de lier le mélange, et on ne lésine pas sur la quantité d’herbes et de légumes verts feuillus : persil, coriandre, aneth, épinards et laitue prennent part au défilé, aux côtés des noix et des canneberges séchées (ou des baies de berbéris, pour une touche iranienne plus authentique).", itemChef: ["1", "5 ans ", "1M"], picRecipe: "kukusabzi")
var chefZanoni: Chef = Chef(pictureChef: "zanoni", nameChef: "Zanoni", prenom: "Simone", bioChef: "Simone Zanoni grandit en Lombardie, dans une ferme à Provaglio Val Sabbia, près du lac de Garde. Il est initié tôt à la cuisine : sa famille réalise ses propres charcuteries, légumes, fromages. L'été, il rend visite à ses grands-parents à la montagne et aide son grand-père à faire des fromages et sa grand-mère à réaliser des tortellini. Cette dernière lui apprend beaucoup techniquement, notamment sur les cuissons", bioPlat: "La caponata est une spécialité culinaire à base d'aubergines, d'oignons, de tomates, de céleri, d'olives vertes et de câpres. Les légumes sont cuits avec un verre de vinaigre et un peu d'huile d'olive. Ce plat se mange chaud ou froid.", itemChef: ["1", "5 ans ", "1M "], picRecipe: "caponata")
var chefDadah: Chef = Chef(pictureChef: "chefDadah", nameChef: "Djellah", prenom: "Dadah", bioChef: "une passion de cuisinier a était crée au coeur de chef Dadah depuis l'àge de 18 ans avec sa grand mére,jusqu'a 23 ans, avant de s'installer en France. Mère de 2 enfants, elle aime cuisiner pour sa famille. Au fil des années et des voyages, elle perfectionne les recettes de son enfance et de sa jeunesse avant de finalement se décider en 2010 à les partager sur son blog Les Joyaux de Dadah. Elle présente aujourd'hui une émission culinaire quotidienne sur Samira TV ", bioPlat: "La chakhchoukha est un mets de fête se composant de pâte de semoule émiettée, cuite à la poêle, arrosée de sauce tomate rouge à la viande, épicée, de pois chiches et, dans quelques régions, de courgettes, de carottes et de navets, de fèves ou encore de pommes de terre. Elle est parfois servie avec du lait fermenté (leben) , Il existe plusieurs variétés de chakhchoukha selon les régions, comme dans les régions algériennes de Biskra, Constantine et Sétif, de Khenchela, de Batna, Annaba et El Oued, même dans le Mzab, le Hoggar, et bien plus encore, à Nefta en Tunisie. La différence consiste dans la nature de la pâte utilisée et dans la méthode de préparation,ainsi que dans l’ajout de fèves, propre à la variante tunisienne, Il y a cependant une particularité distincte dans la variante de la ville de Batna, qui utilise une pâte différente de celle de la galette, qui elle est utilisée dans la région du Sahara. Il s’agit d’une sorte de crêpe cuite sur une plaque de fer. Cette variante est aussi très utilisée dans certaines villes limitrophes de la ville de Bou Saâda, telles que Batna, Barika, M'Sila, Biskra, etc... , La chakhchoukha est le plat culinaire par excellence à Biskra3 mais elle est aussi faite et appréciée dans tous les Aurès et à proximité. Ainsi, si elle est sensiblement identique à Batna, elle est tout autre à Constantine dans sa conception, ou encore à Bou Saâda ou M'sila. En Tunisie, à Nefta4 et à Tozeur, on ajoute le plus souvent des fèves dans la garniture.", itemChef: ["2", "15 ans ", "2M"], picRecipe: "chkhchkh")


var chefTab = [chefMojgan, chefPepone, chefKentRollins, chefBali, chefZanoni, chefAmanda, chefDadah]
