//
//  Recipe.swift
//  Yumood
//
//  Created by apprenant75 on 20/09/2022.
//

import Foundation

struct Recipe: Identifiable {
    let id = UUID()
    var nameRecipe : String
    var imgRecipe: String
    var ingredientsRecipe : [String]
    let stepsRecipe : String
    var chef : Chef
    var continent: String
    var country: String
    var video: String
    var time: Int
    var isLiked:Int = 0
    var quantity: [String]
}
var arepa: Recipe = Recipe(nameRecipe: "Arepa", imgRecipe: "arepaRica", ingredientsRecipe: ["farine de maiz","sel","eau","huile d'olive"], stepsRecipe: "1 verser la farine dans deux fois la quantité d'eau,\n 2 remuer lentement jusqu'à obtenir une patte molle, \n3 verser une 1 centilitre d'huile d'olive,\n 4 modeler avec la patte une galette ronde", chef: chefAmanda, continent: "Amérique", country: "Colombie", video: "KK88WkcAT00", time: 30, quantity: ["500g", "10g", "500ml", "50cl"])
var pizzaMargueritta: Recipe = Recipe(nameRecipe: "Pizza Marguerita", imgRecipe: "pizzamargarita", ingredientsRecipe: ["400 g farine", "22 cl d'eau tiède", "3 g de levure de boulanger sèche (une cuillère à café)","6 g de sel fin (2 cuillères à café)","une pincée de sucre (facultatif)","une cuillère à soupe d’huile d’olive vierge extra (facultatif)", "300 g de coulis de tomate ou de tomates en boîte de qualité", "150 g de mozzarella", "4 feuilles de basilic"], stepsRecipe: "Verser la farine dans un saladier, ajouter le sel et mélanger. Ajouter la levure sèche, le sucre, le sel et mélanger. Creuser un puit au centre, y verser l’eau. Petit à petit, à l’aide d’une fourchette, y incorporer la farine. Pétrir ensuite à la main ou dans un robot-pétrisseur, ajouter l’huile puis continuer à pétrir jusqu’à obtenir une pâte lisse (éventuellement la transférer sur le plan de travail légèrement fariné pour la pétrir plus facilement). La façonner en boule, la mettre dans un grand saladier et couvrir avec un linge propre. Laisser la pâte lever pendant 2 heures. (Elle doit doubler de volume., Dégazer la pâte sur un plan de travail, la pétrir rapidement à nouveau, puis l’étaler dans un moule à pizza ou sur une plaque de cuisson. Etaler la pâte plus ou moins fine, selon l’épaisseur que vous voulez donner à la pizza. Etaler si possible à la main, la pâte reste plus aérienne. Faire lever la pâte étalée dans le moule pendant encore 1 heure.La garniture :Ajouter la sauce tomate en la répartissant avec une petite louche, en laissant 1,5 cm de bord libre tout autour de la pâte. Ajouter la mozzarella préalablement coupée en dés (ou en tranches) et dégorgée.Faire cuire la pizza à 210°C pendant 10 à 15 minutes. Dès la sortie du four y ajouter quelques feuille de basilic frais et servir.", chef: chefPepone,  continent: "Europe", country: "Italie", video: "FHk_7LtYPhE", time: 120, quantity: ["500g", "10g", "500ml", "50cl"])
var nasiGoreng: Recipe = Recipe(nameRecipe: "Nasi Goreng", imgRecipe: "nasigoreng", ingredientsRecipe: ["4 tasses de riz au jasmin cuit froid (21 onces; 600g) ou autre riz à grain moyen à long (voir notes)", "2 cuillères à soupe (30 ml) d'huile neutre, comme l'huile de canola ou de tournesol", "2 cuillères à soupe (30 ml ) kecap manis (voir notes), plus plus pour arroser", "2 cuillères à café (10 ml) de sauce soja", "Sel casher", "Poivre blanc moulu"], stepsRecipe: "1 transférer le riz dans un bol et briser le riz avec vos mains en grains individuels, Chauffer l'huile dans un grand wok ou une poêle à feu vif jusqu'à ce qu'elle frémisse. Ajouter la pâte d'épices et cuire, en remuant constamment et en raclant le fond du wok ou de la casserole pour empêcher la pâte de brûler,Répartir le riz entre deux assiettes et garnir chaque assiette de riz d'un œuf au plat. Garnir de tranches de concombre et de tomate et arroser d'échalotes frites, si vous le souhaitez.", chef: chefBali, continent: "asie", country: "Indonesie", video: "SG6itbjUCuA", time: 60, quantity: ["500g", "10g", "500ml", "50cl"])
var damperRecipe: Recipe = Recipe(nameRecipe: "Damper", imgRecipe: "damper", ingredientsRecipe: ["6 morceaux de bacon épais hachés, 1 oignon jaune coupé en dés, 4 tasses de farine tout usage et plus pour saupoudrer, 2 grosses cuillères à soupe de bicarbonate de soude, 1 cuillère à café de sel, 1 ⅓ boîtes de lait évaporé et plus au besoin"], stepsRecipe: "1-Dans une poêle en fonte à feu moyen, ajouter le bacon et le faire cuire environ 4 minutes. Incorporer l'oignon et continuer à cuire jusqu'à ce que, 2-Ajouter la farine, le bicarbonate de soude et le sel dans un grand bol et bien mélanger . Incorporer le lait, 1/2 boîte à la fois, et incorporer à la cuillère. Continuer d'ajouter du lait jusqu'à ce qu'une boule de pâte se forme. Vous ne voulez pas qu'elle colle, 3- Videz la pâte sur une surface farinée puis ajouter le bacon et les oignons sur le dessus. Pétrir pendant environ 5 minutes, et le bacon et les oignons sont mélangés uniformément. Aplatir la pâte à environ 1½ pouce d'épaisseur et saupoudrer abondamment l'extérieur avec de la farine, Cendres blanches chaudes. Couvrir légèrement la pâte sur le dessus avec plus de cendres et laisser cuire pendant environ 45 à 55 minutes. L'amortisseur fini doit sonner creux lorsque vous le frappez.", chef: chefKentRollins, continent: "Oceanie", country: "Australie", video: "PLevsQuf4XY", time: 60, quantity: ["500g", "10g", "500ml", "50cl"])
var kukuSabzi: Recipe = Recipe(nameRecipe: "Kuku Sabzi", imgRecipe: "kukusabzi", ingredientsRecipe: ["Poireau, haché", "Oignons verts, hachés ", "Huile d’olive", "Persil ciselé finement ", "Coriandre ciselée finement", "Aneth ciselé finement ", "Epinards hachés finement ", "Laitue hachée finement", " Oeufs ", "Curcuma ", "Sel", "Poivre noir moulu ", "Noix de Grenoble entières ", "Canneberges séchées non sucrées ou baies de berbéris"], stepsRecipe: "1. Dans une grande poêle à feu moyen-élevé, attendrir le poireau et les oignons verts dans 30 ml (2 c. à soupe) de l’huile. Ajouter les herbes, les épinards et la laitue. Poursuivre la cuisson 2 minutes en remuant. Égoutter.\n \n2. Dans un bol, mélanger au fouet les œufs, le curcuma, le sel et le poivre. Ajouter le mélange d’herbes, les noix et les canneberges.\n \n3. Placer la grille au centre du four. Préchauffer le four à gril (broil). \n \n4. Dans une poêle antiadhésive d’environ 20 cm (8 po) de diamètre allant au four, à feu moyen, verser le mélange d’œufs dans le reste de l’huile. Couvrir et cuire 5 minutes ou jusqu’à ce que la bordure commence à dorer. Retirer le couvercle et poursuivre la cuisson au four 3 minutes.\n \n5.Démouler sur une assiette", chef: chefMojgan, continent: "Asie", country: "Iran", video: "zXWYHYamXzQ", time: 45, quantity: ["1", "8", "45ml", "90 g", "90g", "45g", "60g", "50g", "5", "2.5ml", "2.5ml", "2.5ml", "50g", "15ml"])
var caponata: Recipe = Recipe(nameRecipe: "Caponata", imgRecipe: "caponata", ingredientsRecipe: ["500g d'aubergine", "50g de câpres", "2 poivrons", "1 oignon", "3 tomates", "4 c. d'huile d'olive", "7cl de vinaigre", "50g d'olives vertes", "sel", "poivre"], stepsRecipe: "1. Couper les aubergines et les poivrons en petits dés. 2. Les faire revenir dans 3 cuillère à soupe d'huile pendant 15 minutes. 3. Dans une autre casserole, faire chauffer le reste de l'huile. Y jeter les oignons émincés. Lorsqu'ils sont dorés, ajouter les tomates pelées, épépinées et concassées. Laisser mijoter 10 minutes puis incorporer les câpres, les olives dénoyautées et la branche de céleri finement émincée. Mélanger bien puis ajouter les aubergines et les poivrons. 4. Mouiller avec le vinaigre et l'eau. Saler, poivrer et sucrer. 5. Laisser cuire à découvert pendant 15 minutes pour que le vinaigre s'évapore et que le mélange épaississe légèrement.", chef: chefZanoni, continent: "Europe", country: "Italie", video: "4BfVlG_wjTc", time: 30, quantity: ["500g", "10g", "500ml", "50cl"])
var chakhchoukha: Recipe = Recipe(nameRecipe: "Chakhchoukha", imgRecipe: "chkhchkh", ingredientsRecipe: [ ".Pack feuilles de msemen", ".500G Viande d'agneau", ".1 Oingnon", ".22CL Huile", ".2 C. à c. ras el-hanout", ".2 C.à.S Tomate concentré", "2 Gousses d'ail", ".2 C.à.c Paparika", ".Sel, .1 Boite de pois chiches égouttés", ".6 Pommes de terre moyenne" , ".2 Courgette", ".3 Carrot moyen", ".70 CL D'eau"], stepsRecipe: "Préparez la sauce, Pelez puis émincez l’oignon et l’ail, Dans une cocotte, faites chauffer l’huile, ajoutez l’oignon et les morceaux de viande et faites-les colorer de chaque côté, Ajoutez l’ail, le concentré de tomate, un peu de sel, les épices et mélangez. Ajoutez 70 cl d’eau et portez à ébullition., Baissez le feu, couvrez et laissez mijoter pendant 1h30.", chef: chefDadah, continent: "afrique", country: "Algerie", video: "qe8uJ8uBwm0", time: 60, quantity: ["500g", "10g", "500ml", "50cl"])

var kukuSibzamini: Recipe = Recipe(nameRecipe: "Kuku Sibzamini", imgRecipe: "kukuSibzamini", ingredientsRecipe: ["Grosses pommes de terre", "Gros oignon", "Gousses d'ail", "Oeufs", "Levure", "Curcuma", "Safran", "Huile de tournesol", "Sel & poivre"], stepsRecipe: "1. Cuire les pommes de terre à l'eau et les raper ou les écraser dans un saladier.\n \n 2. Faire frire les oignons dans une poêle à part et couper finement l'ail \n \n 3. Ajouter les 4 oeufs, les oignons cuits, l'ail émincé, la levure, le curcuma, le safran (optionnel) du sel et du poivre aux pommes de terre rapées ou écrasées. \n \n 4. Faites chauffer de l'huile de tournesol dans une poêle. Formez avec vos mains des petites croquettes rondes, baissez le feu et ajoutez les koukou dans la poêle. \n \n 5. Laisser frire le Koukou Sibzamini d'un côté puis le retourner \n \n 6.Sortez votre koukou de la poêle et essorez-le à l'aide d'un papier sopalin pour retirer la matière grasse.", chef: chefMojgan, continent: "Asie", country: "Iran", video: "ddCTnKWAobY", time: 30, quantity: ["4", "1", "2", "2", "1 cuillère à café", "1 cuillère à café", "1/2 cuillère à café", "", ""])

var recipeTab = [kukuSabzi, kukuSibzamini, arepa, pizzaMargueritta, nasiGoreng, damperRecipe, caponata, chakhchoukha]
